apiVersion: v1
kind: Service
metadata:
  name: botter-app
  namespace: botter
  labels:
    app: botter-app
spec:
  selector:
    app: botter-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP