apiVersion: v1
kind: Service
metadata:
  name: botter-db
  namespace: botter
  labels:
    app: botter-db
spec:
  selector:
    app: botter-db
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP