apiVersion: v1
kind: Service
metadata:
  name: botter-redis
  namespace: botter
  labels:
    app: botter-redis
spec:
  selector:
    app: botter-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP